USE AMAZONEBOOKS;

USE SCHEMA PUBLIC;

CREATE OR REPLACE STAGE amazone_books_stage
FILE_FORMAT = (TYPE= csv FIELD_DELIMITER = ',' FIELD_OPTIONALLY_ENCLOSED_BY = '"');

CREATE OR REPLACE TABLE amazone_books (
	BOOK_ID NUMBER(38,0) NOT NULL,
	BOOK_TITLE VARCHAR(16777216),
	BOOK_AMOUNT FLOAT,
	BOOK_AUTHOR VARCHAR(16777216),
	BOOK_RATING FLOAT,
	BOOK_LINK VARCHAR(16777216),
	BUSINESS_DATE DATE
);


INSERT INTO CONFIG.TABLE_CONFIG VALUES ('amazone_books','2024-02-29');

INSERT INTO CONFIG.TBL_PRIMARY_KEY VALUES ('amazone_books','book_id',1,1);