USE AMAZONEBOOKS;

USE SCHEMA PUBLIC;


CREATE OR REPLACE STAGE amazonebook_reviews_stage
FILE_FORMAT = (TYPE= csv FIELD_DELIMITER = ',' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 );

CREATE OR REPLACE TRANSIENT TABLE AMAZONEBOOK_REVIEWS (
	BOOK_ID NUMBER(38,0),
	REVIEWER_NAME VARCHAR(16777216),
	RATING FLOAT,
	REVIEW_TITLE VARCHAR(16777216),
	REVIEW_CONTENT VARCHAR(16777216),
	REVIEWED_ON DATE,
	BUSINESS_DATE DATE
);

-- Insert Last Extract Date
INSERT INTO CONFIG.TABLE_CONFIG VALUES ('amazonebook_reviews','2024-02-29');

-- Insert Primary Keys
INSERT INTO CONFIG.TBL_PRIMARY_KEY VALUES 
('amazonebook_reviews','book_id',1,1),
('amazonebook_reviews','reviewer_name',2,2),
('amazonebook_reviews','business_date',3,7);



