CREATE DATABASE AMAZONEBOOKS;

USE AMAZONEBOOKS;

-- CREATING CONFIG DDLS

CREATE SCHEMA CONFIG;

USE SCHEMA CONFIG;

CREATE OR REPLACE TRANSIENT TABLE CONFIG.TABLE_CONFIG (
	TABLE_NAME TEXT,
	LAST_EXTRACT_DATE DATE
);

CREATE OR REPLACE TRANSIENT TABLE CONFIG.TBL_PRIMARY_KEY (
	TABLE_NAME TEXT,
	PRIMARY_COLUMN TEXT,
	ORDINAL_POSITION NUMBER(38,0),
	STAGE_POSITION NUMBER(38,0)
);